### PR TITLE
Follow-up to Chosen library fixes

### PR DESCRIPTION
**Pull request by davereid**
If you add a 'new' option inside the 'Unit of measure' field chosen widget, it does not auto-select the 'Other' option in the select list. I also fixed deims_variable.field.inc to use the #chosen FAPI property for that element instead of a class name, which is more reliable now.

### CODE REVIEW

**Comment by isangil** [comment]
.. for example, around line 1350.. or so of 'data_set.features.field.inc', Dave, is it safe to assume it'd be good to add to this branch similar changes?

```
        'module' => 'options',
        'settings' => array(
          'apply_chosen' => 0,
        ),
        'type' => 'options_select',
        'weight' => '78',
```

i can hunt down those too..

**Comment by isangil** [comment]
person field feature, line 996 or so

```
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(
          'apply_chosen' => 0,
        ),
        'type' => 'options_select',
```

**Comment by isangil** [comment]
data source field at 381

```
        'module' => 'options',
        'settings' => array(
          'apply_chosen' => 0,
        ),
        'type' => 'options_select',
        'weight' => '10',
      ),
```

just annotating instances -

**Comment by davereid** [comment]
Yeah I reviewed those two and they are instances we actually don't want Chosen: like 'Is this EML valid?' or 'CSV orientation' (only has two values). The change in deims_person should be included already in this PR.

**Comment by davereid** [comment]
After this I swear no more Chosen module releases or follow-ups.

**Comment by isangil** [comment]
well great, let's push these commits to 7.x and the to Drupal THANKS Dave!

**Pull request merged**
